services:
  novosga:
    build: .
    restart: always
    ports:
      - "80:8080"
    environment:
      APP_ENV: ${APP_ENV}
      # database connection
      DATABASE_URL: ${DATABASE_URL}
      APP_LANGUAGE: ${APP_LANGUAGE}
      # Endereço Mercure para publicar mensagem (onde "mercure" é o nome do host)
      # esse endereço será chamado internamente via o PHP
      MERCURE_URL: ${MERCURE_URL}
      # Endereço Mercure para consumir mensagem
      # esse endereço será chamado via o navegador web
      MERCURE_PUBLIC_URL: ${MERCURE_PUBLIC_URL}
  mercure:
    image: novosga/mercure:v0.11
    restart: always
    ports:
      - "3000:3000"
    environment:
      # same value from ports
      SERVER_NAME: ${SERVER_NAME}
      # default publish key, must be changed
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY}
      MERCURE_EXTRA_DIRECTIVES:  ${MERCURE_EXTRA_DIRECTIVES}